name: Solver Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Solver Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set nightly mode
        run: rustup override set nightly

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --release --manifest-path pdf-generator/Cargo.toml
